#PostgreSQL connection config
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reservatusala-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
#Application config
server:
  port: 8081
#JWT config
jwt:
  secret: S3CrEtK3Yh$$k3kjgk3j23jkgll.tt32h1gh21gh1gh1hjl1s&
  expiration-seconds: 31536000
